### PR TITLE
feat(op): Add response_mode: form_post

### PR DESCRIPTION
**Pull request by ay4toh5i**
As mentioned in this issue(https://github.com/zitadel/oidc/issues/515), the implementation of `form_post` is being requested. Additionally, as mentioned in this issue(#550) as well, there are issues with the current implementation of response_mode. 
It is crucial to establish a secure method of returning Authorization Response in the implicit flow.

According to the [OAuth 2.0 Form Post Response Mode](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html) specification, it is considered safe to return Authorization Response parameters using the form_post Response Mode even if the parameter's default response mode is set to the query or the fragment.

> 4.  Security Considerations
As described in [OAuth 2.0 Multiple Response Type Encoding Practices](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html#OAuth.Responses) [OAuth.Responses], there are security implications to encoding response values in the query string and in the fragment value. Some of these concerns can be addressed by using the Form Post Response Mode. In particular, it is safe to return Authorization Response parameters whose default Response Modes are the query encoding or the fragment encoding using the form_post Response Mode.

Therefore I have implemented response_mode=form_post as it is considered beneficial.
Any feedback on this implementation would be greatly appreciated.

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by muhlemmer** [comment]
The approach looks good to me. I see the PR is in draft, is there still work to do?

At a first glance I would comment:

1. Parse the template ahead of time in a global variable using template.Must. No need to waste resources on every request.
2. Render the template in a buffer, so that the error can be handled correctly. As the code is now, Execute can return an error after partial output (and so a 200) is already written.

Once you mark the PR ready for review I will do a final review.

Cheers!

**Comment by ay4toh5i** [comment]
@muhlemmer 
Thank you for the initial review!
I made this PR is ready. And I've addressed the feedback, so please take a look.

**Comment by muhlemmer** [comment]
I get a bunch of compile errors when I build your branch:

```
# github.com/zitadel/oidc/v3/pkg/op_test [github.com/zitadel/oidc/v3/pkg/op.test]
pkg/op/auth_request_test.go:12:2: "time" imported and not used
pkg/op/auth_request_test.go:1122:6: unknown field ResponseMode in struct literal of type storage.AuthRequest
```

**Comment by muhlemmer** [comment]
Another comment, I just reread the [OAuth 2.0 Form Post Response Mode, section 2.  Form Post Response Mode](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html#FormPostResponseMode) and there is also the following requirement:

> Because the Authorization Response is intended to be used only once, the Authorization Server MUST instruct the User Agent (and any intermediaries) not to store or reuse the content of the response.

So a [`Cache-Control: no-store`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives) header must be sent along with the response.

**Comment by ay4toh5i** [comment]
@muhlemmer 
Thank you for your review!

I've addressed your feedback. Could you please review it once?
Also, regarding the tests, I've added `RESPONSE_MODE` to the example app for testing, and I've also tested it with the following URLs:
In both cases, the client's implementation is still pending, so I'm checking the request contents in the console.

`http://localhost:9998/auth?client_id=web&prompt=Welcome back!&redirect_uri=http://localhost:9999/auth/callback&response_type=id_token&response_mode=form_post&scope=openid&state=751c4627-0a02-47e3-8630-bde7611964ad`

`http://localhost:9998/auth?client_id=web&prompt=Welcome back!&redirect_uri=http://localhost:9999/auth/callback&response_type=id_token+token&response_mode=form_post&scope=openid&state=751c4627-0a02-47e3-8630-bde7611964ad`

**Comment by muhlemmer** [comment]
The client implementation is quite simple. But you disabled push access to your PR. I've send a PR against this branch. Once merged, the examples work fine with `RESPONSE_MODE="form_post"` set for the app.

**Comment by ay4toh5i** [comment]
@muhlemmer Thanks a bunch! I've merged your PR.

**Review by muhlemmer — APPROVED** [review]

**Pull request merged**
